# Example docker-compose setup for deploying the bot
# Customize variables in an .env file
version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      # Build for x86_64 even on arm hosts
      platform: linux/amd64
    environment:
      - BOT_API_KEY=${BOT_API_KEY}
      - BOT_API_URL=${BOT_API_URL}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegram-bot.rule=Host(`bot.sherlockramos.tech`)"
      - "traefik.http.routers.telegram-bot.entrypoints=websecure"
      - "traefik.http.routers.telegram-bot.tls=true"
